
strategy:
  matrix:
    ubuntu-py36:
      imageName: 'ubuntu-16.04'
      pythonVersion: '3.6'
    ubuntu-py37:
      imageName: 'ubuntu-16.04'
      pythonVersion: '3.7'
    ubuntu-py38:
      imageName: 'ubuntu-16.04'
      pythonVersion: '3.8'
    macos-py36:
      imageName: 'macos-10.13'
      pythonVersion: '3.6'
    macos-py37:
      imageName: 'macos-10.13'
      pythonVersion: '3.7'
    macos-py38:
      imageName: 'macos-10.13'
      pythonVersion: '3.8'
    windows-py36:
      imageName: 'vs2017-win2016'
      pythonVersion: '3.6'
    windows-py37:
      imageName: 'vs2017-win2016'
      pythonVersion: '3.7'
    windows-py38:
      imageName: 'vs2017-win2016'
      pythonVersion: '3.8'

pool:
  vmImage: $(imageName)

trigger:
- master

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
    architecture: 'x64'

- task: InstallSSHKey@0
  displayName: 'Install deployment key'
  inputs:
    knownHostsEntry: 'github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiwRE42F8TzKvRCdqar9mquyuW1sfQh2sOFLBNHzQ9w0NuwS0/qaHDJ/1fCgWOOmxzk+eQo5ZbglXAHo1gWC8OtIfK9v/dZQ/Wizs3P4zUt1tkitlQir4iujSqHryomshmvu4gnCS1g4WnKd6y/5t8KZzs32Ve2YylJLSkmmAUdyBq/hKOBLd4cwAoQvMS7s6PV/CNtdWHq3TcYvd0s5u6Hv/PSb0LdgHeWLHBNIwWCmQnH4XgKMDFRT/HBYRTbAAy99NHWEdbWvFyKq0bh833bnzK+5Niu7SrW8lwHx6/9sloM45BYtauO0v//xRMrPJyX8Y7wuu9mO3nF++2pZ6d'
    sshKeySecureFile: 'github-deploy-key'

- script: git submodule init && git submodule update
  displayName: 'Load git submodules'

- script: python setup.py install
  displayName: 'Build'

- script: python -m pip install -U pip pytest
  displayName: 'Install test dependencies'

- script: pytest --junitxml=test-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Python $(python.version)'
  condition: succeededOrFailed()
